name: Auto-formatowanie JSON

on: [push, pull_request]

jobs:
  lint-and-format-json:
    runs-on: ubuntu-latest

    steps:
      - name: Pobierz kod z repozytorium
        uses: actions/checkout@v3

      - name: Zainstaluj Prettier
        run: npm install -g prettier

      - name: Sformatuj pliki JSON (autopoprawa)
        run: prettier --write "**/*.json"

      - name: Zapisz poprawione pliki do repozytorium
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Auto-formatowanie JSON plików"
          git push
        continue-on-error: true  # Nie zatrzymuj workflow, jeśli nie ma zmian
